### ISSUE TITLE
Script does not generate anything in the mods folder

### ISSUE THREAD

**Issue by JacobDrivers** [hoverbike1/lazy-pack-generator#1]
The script does not generate anything in the mods folder for the game to use. I think it applies "other" settings, but does not actually make the "mod". I am using the latest mainline Yuzu - portable. I choose the Yuzu directory, etc. 

EDIT: I think I found the issue while typing this... I think it is because I am using Yuzu in portable mode. It seems to be putting the mod/s straight up in the Yuzu directory. I found a new folder "load" that is usually in "\Yuzu\user\" - I guess I can move them into the correct place manually - but, it still may want to be fixed for others as well.

It seems to be working fine when Yuzu is installed typically, and not portable (I tried it on my laptop where it is installed in the /user/ folder and not portable). As the folder structure is "slightly" different.

For portable, you choose the "user" folder, not just "yuzu".

**Comment by hoverbike1** [comment]
![image](https://github.com/hoverbike1/lazy-pack-generator/assets/57139770/e1ef72bd-ac2d-4e14-a08c-ddc160b228c8)
kinda like it says here, or?

**Comment by JacobDrivers** [comment]
> ![image](https://user-images.githubusercontent.com/57139770/254063293-e1ef72bd-ac2d-4e14-a08c-ddc160b228c8.png) kinda like it says here, or?

I didn't even see that. 🤦 That is the only place it is mentioned, as far as I know. I read the guides (It also didn't mention choosing the user folder) and kept looking before opening an issue. I figured it was something simple I was overlooking... I was thinking A LOT of others that use this will start posting/commenting about it as well (Or I am the odd dumb one out, lol).

Anyways, big thanks to the team that has worked on all of this. No words can express the gratitude.

**Comment by hoverbike1** [comment]
i've been struggling to autofill it correctly when looking for a portable folder, isn't as easy as i'd like...

i hope that its a minimal amount of users using portable / linux, but i guess only tell will tell :p

let me know if you have an idea for how to better present this information so it isn't as easily missed

**Comment by JacobDrivers** [comment]
The easiest thing I can think of is just including it in/on the instructions - the image or just text "If you are using portable, choose the user folder" I didn't see it anywhere in the guides, and I assumed something was wrong. 

And, hopefully, maybe people will see this and my mistake, lol. 

Besides this little thing, which is just 1 folder tree off. There really isn't much to do for custom folder paths I guess besides making sure people know to use the user folder. I assume it isn't too easy (Or redundant) to script for every customized folder setup. Just too many variables.

Thank you so much for responding fast, and helping. And thank you for this script! We lazy people of course are going to mess up. lol.

**Comment by hoverbike1** [comment]
ill jot it down on the to-do list for 2.5, see if i can't brainstorm some good layout for providing that information within the app, and add it to the instructions on the primary github.

glad to hear its helping, this script was born out of necessity when chuck made it possible to use just about every resolution / framerate we want - as to not create hundreds of lazy packs, a script was necessary to generate them on the fly with the users preferred settings.
