### ISSUE TITLE
Lazy pack created but ignored

### ISSUE THREAD

**Issue by FrancescoGrazioso** [hoverbike1/lazy-pack-generator#3]
When launching the script the pack is created correctly in the TOTK mod folder

![image](https://github.com/hoverbike1/lazy-pack-generator/assets/40018163/f99c24f1-8ca6-4082-9ee4-c938a265f16d)

The problem is that when launching the game the mods are ignored by Yuzu, running the game at the wrong resolution and FPS

![image](https://github.com/hoverbike1/lazy-pack-generator/assets/40018163/d3f63baa-0d08-4ea8-8b70-8c74a7f651e9)

**Comment by hoverbike1** [comment]
![image](https://github.com/hoverbike1/lazy-pack-generator/assets/57139770/cd3569ed-570f-420f-b5e2-d29e02338c8c)
Are you certain that the mods are enabled?

**Comment by FrancescoGrazioso** [comment]
That's what i see after the script

![image](https://github.com/hoverbike1/lazy-pack-generator/assets/40018163/23625f0a-d216-4788-9636-2055fc7fcbc7)

**Comment by hoverbike1** [comment]
I'm struggling to think of why it isn't applying.
I suspect a bad base game dump.
If this is Fatgirls dump, go ahead and throw it in the garbage bin, please.
Seems that dump won't ever stop bugging us.

**Comment by FrancescoGrazioso** [comment]
Can be possible that you are right, I tried adding mods one by one and still it appears to not work. I'll try with another dump and let you know if it works

**Comment by FrancescoGrazioso** [comment]
I'm closing the issue since it appears not to be a script problem but something with my current config
